'use client';

import './globals.css'
import type { Metadata } from 'next'
import { Inter, Noto_Sans_TC } from 'next/font/google'
import { i18n } from 'i18next';
import { I18nextProvider  } from 'react-i18next';

import { i18nInstance } from '@/app/_locales/i18n';

const inter = Inter({ subsets: ['latin'] })
const notoSansTC = Noto_Sans_TC({ subsets: ['latin'] })

<<<<<<< HEAD
export const metadata: Metadata = {
  title: '第一銀行',
  description: '展覽頁面',
}
=======
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
>>>>>>> a69d1e8 (feat: add i18n modules)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className={notoSansTC.className} >
        {children}
=======
      <body className={inter.className} >
        <I18nextProvider i18n={i18nInstance as i18n}>
          {children}
        </I18nextProvider>
>>>>>>> a69d1e8 (feat: add i18n modules)
      </body>
    </html>
  )
}
